repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/lorenzwalthert/pre-commit-hooks
    rev: v1.9.1
    hooks:
    -   id: styler
        args: [--style_pkg]
    -   id: lintr
    -   id: roxygenize
-   repo: https://github.com/r-lib/actions/tree/master/examples
    rev: v2
    hooks:
    -   id: codemeta-description-updates
