Base population parameters: Value
Generate new base population?: 'FALSE'
Input data for base population: synpop_wave13imp3.csv
Population scale: '1000'
Population adjuster: '1.026'
Synthetic population if not generating a new one: mysim_public.csv
NA: .na.character
Simulation parameters: Value
Simulation start year: '2013'
Simulation length (years): '10'
Probabilistic: 'TRUE'
Number of simulations: '5'
Parallelize: 'TRUE'
Cores: '4'
Calibration mode: 'TRUE'
Set seed: 'TRUE'
