# config/simulation_setup.yml
#
# This file contains the main simulation parameters.
#
# You will need to populate this file with the data from the
# "Simulation inputs" sheet of your ausoa_input_public.xlsx file.

simulation_start_year: 2013
simulation_length_years: 10
probabilistic: true
number_of_simulations: 10
set_seed: true
parallelize: true
calibration_mode: false
input_data_for_base_population: "mysim_public.csv"
population_scale: 100
population_adjuster: 1.0
generate_new_base_population: true
simpop_file: "am.parquet"
