# Workflow for building and checking R package.
#
# For more information, see: https://github.com/r-lib/actions/
#
# This workflow is based on the default 'R-CMD-check' workflow from r-lib/actions.

name: R-CMD-check

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-renv@v2

      - name: Run R CMD check
        run: |
          options(crayon.enabled = TRUE)
          devtools::check(document = FALSE, error_on = "warning")
        shell: Rscript {0}
